INSERT INTO cities VALUES (1,'18 Hazari City',4);
INSERT INTO cities VALUES (2,'Abottabad',1);
INSERT INTO cities VALUES (3,'Ahmed Pur East',5);
INSERT INTO cities VALUES (4,'Ahmed Pur Sial',4);
INSERT INTO cities VALUES (5,'Akhtar Abad',4);
INSERT INTO cities VALUES (6,'Akora Khattak',1);
INSERT INTO cities VALUES (7,'Alaabad',4);
INSERT INTO cities VALUES (8,'Ali Pur',5);
INSERT INTO cities VALUES (9,'Ali Pur Chatta',4);
INSERT INTO cities VALUES (10,'Aminabad',4);
INSERT INTO cities VALUES (11,'Arif Wala',4);
INSERT INTO cities VALUES (12,'Attock',1);
INSERT INTO cities VALUES (13,'Badeh',3);
INSERT INTO cities VALUES (14,'Badin',3);
INSERT INTO cities VALUES (15,'Bahawalnagar',4);
INSERT INTO cities VALUES (16,'Bajawar',1);
INSERT INTO cities VALUES (17,'Bakhsha Pur',3);
INSERT INTO cities VALUES (18,'Bakrani',3);
INSERT INTO cities VALUES (19,'Bala Kot',1);
INSERT INTO cities VALUES (20,'Bannu',1);
INSERT INTO cities VALUES (21,'Basir Pur',4);
INSERT INTO cities VALUES (22,'Bat Khela',1);
INSERT INTO cities VALUES (23,'Bhai Pheru',4);
INSERT INTO cities VALUES (24,'Bhakkar',4);
INSERT INTO cities VALUES (25,'Bhalwal',4);
INSERT INTO cities VALUES (26,'Bhawalpur',5);
INSERT INTO cities VALUES (27,'Bhawana',4);
INSERT INTO cities VALUES (28,'Bhera',4);
INSERT INTO cities VALUES (29,'Bhimber',4);
INSERT INTO cities VALUES (30,'Bhiriya City',3);
INSERT INTO cities VALUES (31,'Bhiriya Road',3);
INSERT INTO cities VALUES (32,'Bhurban',1);
INSERT INTO cities VALUES (33,'Buche Ki',4);
INSERT INTO cities VALUES (34,'Bunir',1);
INSERT INTO cities VALUES (35,'Burewala',5);
INSERT INTO cities VALUES (36,'Chak Jhumra',4);
INSERT INTO cities VALUES (37,'Chakdara',1);
INSERT INTO cities VALUES (38,'Chakwal',1);
INSERT INTO cities VALUES (39,'Chaman',2);
INSERT INTO cities VALUES (40,'Chanda Qila',4);
INSERT INTO cities VALUES (41,'Changa Manga',4);
INSERT INTO cities VALUES (42,'Chani Ghoth',5);
INSERT INTO cities VALUES (43,'Charsadda',1);
INSERT INTO cities VALUES (44,'Chashma',4);
INSERT INTO cities VALUES (45,'Chawinda',4);
INSERT INTO cities VALUES (46,'Chichawatni',4);
INSERT INTO cities VALUES (47,'Chinniot',4);
INSERT INTO cities VALUES (48,'Chishtian',4);
INSERT INTO cities VALUES (49,'Choha Saidan Shah',1);
INSERT INTO cities VALUES (50,'Chowk Azam',5);
INSERT INTO cities VALUES (51,'Chundiko',3);
INSERT INTO cities VALUES (52,'Chunian',4);
INSERT INTO cities VALUES (53,'Dadu',3);
INSERT INTO cities VALUES (54,'Dakhan',3);
INSERT INTO cities VALUES (55,'Dara Adam Khel',1);
INSERT INTO cities VALUES (56,'Dargai',1);
INSERT INTO cities VALUES (57,'Daska',4);
INSERT INTO cities VALUES (58,'Deharki',3);
INSERT INTO cities VALUES (59,'Depalpur',4);
INSERT INTO cities VALUES (60,'Dera Allah Yar',3);
INSERT INTO cities VALUES (61,'Dera Ghazi Khan',5);
INSERT INTO cities VALUES (62,'Dera Ismail Khan',4);
INSERT INTO cities VALUES (63,'Dera Murad Jamali',3);
INSERT INTO cities VALUES (64,'Derya Khan',4);
INSERT INTO cities VALUES (65,'Dhodak',5);
INSERT INTO cities VALUES (66,'Digri',3);
INSERT INTO cities VALUES (67,'Dijkot',4);
INSERT INTO cities VALUES (68,'Dina',4);
INSERT INTO cities VALUES (69,'Dinga',4);
INSERT INTO cities VALUES (70,'Dir',1);
INSERT INTO cities VALUES (71,'Dokri',3);
INSERT INTO cities VALUES (72,'Dunya Pur',5);
INSERT INTO cities VALUES (73,'Emin Abad More',4);
INSERT INTO cities VALUES (74,'Esa Khel',4);
INSERT INTO cities VALUES (75,'Faisalabad',4);
INSERT INTO cities VALUES (76,'Farooqabad',4);
INSERT INTO cities VALUES (77,'Fateh Jang',1);
INSERT INTO cities VALUES (78,'Fateh Pur',5);
INSERT INTO cities VALUES (79,'Fazal Pura',4);
INSERT INTO cities VALUES (80,'Feroze Wattan',4);
INSERT INTO cities VALUES (81,'Gadoon Amazai',1);
INSERT INTO cities VALUES (82,'Gadoon',1);
INSERT INTO cities VALUES (83,'Gago Mandi',5);
INSERT INTO cities VALUES (84,'Gakhar Mandi',4);
INSERT INTO cities VALUES (85,'Gambat',3);
INSERT INTO cities VALUES (86,'Garh More',4);
INSERT INTO cities VALUES (87,'Garhi Yaseen',3);
INSERT INTO cities VALUES (88,'Gari Habibullah',1);
INSERT INTO cities VALUES (89,'Gawadar',3);
INSERT INTO cities VALUES (90,'Ghazi Abad',4);
INSERT INTO cities VALUES (91,'Ghos Pur',3);
INSERT INTO cities VALUES (92,'Ghotki',3);
INSERT INTO cities VALUES (93,'Gilgit',1);
INSERT INTO cities VALUES (94,'Godh Pur',4);
INSERT INTO cities VALUES (95,'Gojra',4);
INSERT INTO cities VALUES (96,'Golarchi',3);
INSERT INTO cities VALUES (97,'Gujjar Khan',1);
INSERT INTO cities VALUES (98,'Gujranwala',4);
INSERT INTO cities VALUES (99,'Gujrat',4);
INSERT INTO cities VALUES (100,'Habib Abad',4);
INSERT INTO cities VALUES (101,'Hafiz Abad',4);
INSERT INTO cities VALUES (102,'Haji Pura',4);
INSERT INTO cities VALUES (103,'Hala',3);
INSERT INTO cities VALUES (104,'Halani',3);
INSERT INTO cities VALUES (105,'Hangu',1);
INSERT INTO cities VALUES (106,'Hari Pur',1);
INSERT INTO cities VALUES (107,'Haroon Abad',4);
INSERT INTO cities VALUES (108,'Hassan Abdal',1);
INSERT INTO cities VALUES (109,'Havalian',1);
INSERT INTO cities VALUES (110,'Hawaili Lakha',4);
INSERT INTO cities VALUES (111,'Hingorja',3);
INSERT INTO cities VALUES (112,'Hub',3);
INSERT INTO cities VALUES (113,'Hujra Shah Muqeem',4);
INSERT INTO cities VALUES (114,'Hyderabad',3);
INSERT INTO cities VALUES (115,'Iskender Abad',4);
INSERT INTO cities VALUES (116,'Islamabad',1);
INSERT INTO cities VALUES (117,'Jacobabad',3);
INSERT INTO cities VALUES (118,'Jahan Khan',4);
INSERT INTO cities VALUES (119,'Jahanian',5);
INSERT INTO cities VALUES (120,'Jalal Pur Bhattian',4);
INSERT INTO cities VALUES (121,'Jalal Pur Pirwala',5);
INSERT INTO cities VALUES (122,'Jalal Pura',4);
INSERT INTO cities VALUES (123,'Jalapur Jatan',4);
INSERT INTO cities VALUES (124,'Jam Nawaz Ali',3);
INSERT INTO cities VALUES (125,'Jampur',5);
INSERT INTO cities VALUES (126,'Jamshoro',3);
INSERT INTO cities VALUES (127,'Jan Pur',5);
INSERT INTO cities VALUES (128,'Jand',1);
INSERT INTO cities VALUES (129,'Jaranwala',4);
INSERT INTO cities VALUES (130,'Jehangura',1);
INSERT INTO cities VALUES (131,'Jehlum',4);
INSERT INTO cities VALUES (132,'Jhang',4);
INSERT INTO cities VALUES (133,'Jhuddo',3);
INSERT INTO cities VALUES (134,'Joharabad',4);
INSERT INTO cities VALUES (135,'Kabir Wala',5);
INSERT INTO cities VALUES (136,'Kahuta',1);
INSERT INTO cities VALUES (137,'Kakul',1);
INSERT INTO cities VALUES (138,'Kala Bagh',4);
INSERT INTO cities VALUES (139,'Kalat',2);
INSERT INTO cities VALUES (140,'Kallar Kahar',1);
INSERT INTO cities VALUES (141,'Kallar Saidan',1);
INSERT INTO cities VALUES (142,'Kamalia',4);
INSERT INTO cities VALUES (143,'Kamber Ali Khan',3);
INSERT INTO cities VALUES (144,'Kamer Mishani',4);
INSERT INTO cities VALUES (145,'Kamoke',4);
INSERT INTO cities VALUES (146,'Kamra',1);
INSERT INTO cities VALUES (147,'Kandh Kot',3);
INSERT INTO cities VALUES (148,'Kandiaree',3);
INSERT INTO cities VALUES (149,'Kandiaro',3);
INSERT INTO cities VALUES (150,'Karachi',3);
INSERT INTO cities VALUES (151,'Karak',1);
INSERT INTO cities VALUES (152,'Kashmore',3);
INSERT INTO cities VALUES (153,'Kasouwal',4);
INSERT INTO cities VALUES (154,'Kasur',4);
INSERT INTO cities VALUES (155,'Khairpur',3);
INSERT INTO cities VALUES (156,'Khairpur Nathan Shah',3);
INSERT INTO cities VALUES (157,'Khan Bela',5);
INSERT INTO cities VALUES (158,'Khan Ka Dogran',4);
INSERT INTO cities VALUES (159,'Khanewal',5);
INSERT INTO cities VALUES (160,'Khanpur',5);
INSERT INTO cities VALUES (161,'Khanpur  Mahar',3);
INSERT INTO cities VALUES (162,'Khanpur Shomali',5);
INSERT INTO cities VALUES (163,'Kharian',4);
INSERT INTO cities VALUES (164,'Khaur',1);
INSERT INTO cities VALUES (165,'Khewra',1);
INSERT INTO cities VALUES (166,'Khipro',3);
INSERT INTO cities VALUES (167,'Khora',3);
INSERT INTO cities VALUES (168,'Khudiyan Khas',4);
INSERT INTO cities VALUES (169,'Khurian Wala',4);
INSERT INTO cities VALUES (170,'Khushab',4);
INSERT INTO cities VALUES (171,'Khuzdar',2);
INSERT INTO cities VALUES (172,'Kohat',1);
INSERT INTO cities VALUES (173,'Kot Addu',5);
INSERT INTO cities VALUES (174,'Kot Banglow',3);
INSERT INTO cities VALUES (175,'Kot Chandana',4);
INSERT INTO cities VALUES (176,'Kot Chutta',5);
INSERT INTO cities VALUES (177,'Kot Diggi',3);
INSERT INTO cities VALUES (178,'Kot Ghulam Mohd',3);
INSERT INTO cities VALUES (179,'Kot Momen',4);
INSERT INTO cities VALUES (180,'Kot Najeeb Ullah',1);
INSERT INTO cities VALUES (181,'Kot Qaisrani',5);
INSERT INTO cities VALUES (182,'Kot Radha Kishan',4);
INSERT INTO cities VALUES (183,'Kotla',4);
INSERT INTO cities VALUES (184,'Kotli Loharan',4);
INSERT INTO cities VALUES (185,'Kotri',3);
INSERT INTO cities VALUES (186,'Kuldana',1);
INSERT INTO cities VALUES (187,'Kumb',3);
INSERT INTO cities VALUES (188,'Kundian',4);
INSERT INTO cities VALUES (189,'Kunri',3);
INSERT INTO cities VALUES (190,'Lahore',4);
INSERT INTO cities VALUES (191,'Lakhi Ghulam Shah',3);
INSERT INTO cities VALUES (192,'Laki Marwat',1);
INSERT INTO cities VALUES (193,'Lala Musa',4);
INSERT INTO cities VALUES (194,'Lalian',4);
INSERT INTO cities VALUES (195,'Larkana',3);
INSERT INTO cities VALUES (196,'Lary Adda',1);
INSERT INTO cities VALUES (197,'Lawrance Pur',1);
INSERT INTO cities VALUES (198,'Layyah',5);
INSERT INTO cities VALUES (199,'Liaqat Pur',5);
INSERT INTO cities VALUES (200,'Lodhran',5);
INSERT INTO cities VALUES (201,'Loralai',2);
INSERT INTO cities VALUES (202,'Losar Sharif',1);
INSERT INTO cities VALUES (203,'Lower Topa',1);
INSERT INTO cities VALUES (204,'Mailsi',5);
INSERT INTO cities VALUES (205,'Makli',3);
INSERT INTO cities VALUES (206,'Malakand*',1);
INSERT INTO cities VALUES (207,'Malakwal',4);
INSERT INTO cities VALUES (208,'Mandi Bhauddin',4);
INSERT INTO cities VALUES (209,'Mandra',1);
INSERT INTO cities VALUES (210,'Manga Mandi',4);
INSERT INTO cities VALUES (211,'Mangla',4);
INSERT INTO cities VALUES (212,'Mankeera',4);
INSERT INTO cities VALUES (213,'Manna Wala',4);
INSERT INTO cities VALUES (214,'Mansehra',1);
INSERT INTO cities VALUES (215,'Mardan',1);
INSERT INTO cities VALUES (216,'Matiari',3);
INSERT INTO cities VALUES (217,'Matli',3);
INSERT INTO cities VALUES (218,'Mehar',3);
INSERT INTO cities VALUES (219,'Mehmood Kot',5);
INSERT INTO cities VALUES (220,'Mehrabpur',3);
INSERT INTO cities VALUES (221,'Mianchannu',4);
INSERT INTO cities VALUES (222,'Mianwali',4);
INSERT INTO cities VALUES (223,'Mingora',1);
INSERT INTO cities VALUES (224,'Mir Ali',1);
INSERT INTO cities VALUES (225,'Miran Shah',1);
INSERT INTO cities VALUES (226,'Mirpur Khas',3);
INSERT INTO cities VALUES (227,'Mirpur Mathelo',3);
INSERT INTO cities VALUES (228,'Mithi',3);
INSERT INTO cities VALUES (229,'Miyani',1);
INSERT INTO cities VALUES (230,'More Khunda',4);
INSERT INTO cities VALUES (231,'Moro',3);
INSERT INTO cities VALUES (232,'Multan',5);
INSERT INTO cities VALUES (233,'Muridke',4);
INSERT INTO cities VALUES (234,'Murree',1);
INSERT INTO cities VALUES (235,'Muzaffar Garh',5);
INSERT INTO cities VALUES (236,'Muzaffarabad',1);
INSERT INTO cities VALUES (237,'Nankana Sahib',4);
INSERT INTO cities VALUES (238,'Narang Mandi',4);
INSERT INTO cities VALUES (239,'Narowal',4);
INSERT INTO cities VALUES (240,'Naseerabad',3);
INSERT INTO cities VALUES (241,'Naukot',3);
INSERT INTO cities VALUES (242,'Nawab Shah',3);
INSERT INTO cities VALUES (243,'Nawan Sher',1);
INSERT INTO cities VALUES (244,'Nokhar Mandi',4);
INSERT INTO cities VALUES (245,'Noshehro Feroz',3);
INSERT INTO cities VALUES (246,'Noshera Virkan',4);
INSERT INTO cities VALUES (247,'Noudero',3);
INSERT INTO cities VALUES (248,'Nowshera',1);
INSERT INTO cities VALUES (249,'Okara',4);
INSERT INTO cities VALUES (250,'Okara Cantt',4);
INSERT INTO cities VALUES (251,'Osta Mohammad',3);
INSERT INTO cities VALUES (252,'Pabbi',1);
INSERT INTO cities VALUES (253,'Pakpattan',4);
INSERT INTO cities VALUES (254,'Pano Aqil',3);
INSERT INTO cities VALUES (255,'Pasroor',4);
INSERT INTO cities VALUES (256,'Pattoki',4);
INSERT INTO cities VALUES (257,'Peshawar',1);
INSERT INTO cities VALUES (258,'Phalia',4);
INSERT INTO cities VALUES (259,'Pind Dadan Khan',1);
INSERT INTO cities VALUES (260,'Pindi Gheb',1);
INSERT INTO cities VALUES (261,'Piplan',4);
INSERT INTO cities VALUES (262,'Pir Jo Goth',3);
INSERT INTO cities VALUES (263,'Pir Mahal',4);
INSERT INTO cities VALUES (264,'Qasba Gujrat',5);
INSERT INTO cities VALUES (265,'Qila Deedar Singh',4);
INSERT INTO cities VALUES (266,'Quetta',2);
INSERT INTO cities VALUES (267,'Rabwah (Chanab Nagar)',4);
INSERT INTO cities VALUES (268,'Rahim Yar Khan',5);
INSERT INTO cities VALUES (269,'Raiwind',4);
INSERT INTO cities VALUES (270,'Rajanpur',5);
INSERT INTO cities VALUES (271,'Ranipur',3);
INSERT INTO cities VALUES (272,'Rato Dero',3);
INSERT INTO cities VALUES (273,'Rawalpindi',1);
INSERT INTO cities VALUES (274,'Rawat',1);
INSERT INTO cities VALUES (275,'Renala Khurrd',4);
INSERT INTO cities VALUES (276,'Risal  Pur',1);
INSERT INTO cities VALUES (277,'Rohri',3);
INSERT INTO cities VALUES (278,'Sadiq Abad',5);
INSERT INTO cities VALUES (279,'Sadu Sharif',1);
INSERT INTO cities VALUES (280,'Sahiwal',4);
INSERT INTO cities VALUES (281,'Sajawal',3);
INSERT INTO cities VALUES (282,'Sakrand',3);
INSERT INTO cities VALUES (283,'Saleh Pat',3);
INSERT INTO cities VALUES (284,'Samaro',3);
INSERT INTO cities VALUES (285,'Sambrial',4);
INSERT INTO cities VALUES (286,'Sambrial',4);
INSERT INTO cities VALUES (287,'Samundri',4);
INSERT INTO cities VALUES (288,'Sanghar',3);
INSERT INTO cities VALUES (289,'Sangla Hill',4);
INSERT INTO cities VALUES (290,'Sara - E - Alamgir',4);
INSERT INTO cities VALUES (291,'Saraye Mahajer',4);
INSERT INTO cities VALUES (292,'Sarei Nourang',1);
INSERT INTO cities VALUES (293,'Sargodha',4);
INSERT INTO cities VALUES (294,'Setharja',3);
INSERT INTO cities VALUES (295,'Shabqadar',1);
INSERT INTO cities VALUES (296,'Shah Kot',4);
INSERT INTO cities VALUES (297,'Shah Pur City',4);
INSERT INTO cities VALUES (298,'Shahdad Kot',3);
INSERT INTO cities VALUES (299,'Shahdadpur',3);
INSERT INTO cities VALUES (300,'Shakar Garh',4);
INSERT INTO cities VALUES (301,'Shakardara',1);
INSERT INTO cities VALUES (302,'Sharqpur',4);
INSERT INTO cities VALUES (303,'Shiekhupura',4);
INSERT INTO cities VALUES (304,'Shikarpur',3);
INSERT INTO cities VALUES (305,'Shinkayari',1);
INSERT INTO cities VALUES (306,'Shor Kot Cantt',4);
INSERT INTO cities VALUES (307,'Shor Kot City',4);
INSERT INTO cities VALUES (308,'Shuja Abad',5);
INSERT INTO cities VALUES (309,'Sialkot',4);
INSERT INTO cities VALUES (310,'Sibbi',2);
INSERT INTO cities VALUES (311,'Sihala',1);
INSERT INTO cities VALUES (312,'Sillanwali',4);
INSERT INTO cities VALUES (313,'Sohawa',4);
INSERT INTO cities VALUES (314,'Sukkur',3);
INSERT INTO cities VALUES (315,'Swabi',1);
INSERT INTO cities VALUES (316,'Swat (Mingora City)',1);
INSERT INTO cities VALUES (317,'Takht Bhai Bazar',1);
INSERT INTO cities VALUES (318,'Talagang',1);
INSERT INTO cities VALUES (319,'Talhar',3);
INSERT INTO cities VALUES (320,'Tando Adam',3);
INSERT INTO cities VALUES (321,'Tando Allahyar',3);
INSERT INTO cities VALUES (322,'Tando Jam',3);
INSERT INTO cities VALUES (323,'Tando Jan Muhammad',3);
INSERT INTO cities VALUES (324,'Tando M Khan',3);
INSERT INTO cities VALUES (325,'Tangi',1);
INSERT INTO cities VALUES (326,'Taranda Muhamamd Panah',5);
INSERT INTO cities VALUES (327,'Tarnol',1);
INSERT INTO cities VALUES (328,'Taunsa Sharif',5);
INSERT INTO cities VALUES (329,'Taxila',1);
INSERT INTO cities VALUES (330,'Terbala',1);
INSERT INTO cities VALUES (331,'Thatta',3);
INSERT INTO cities VALUES (332,'Timergera',1);
INSERT INTO cities VALUES (333,'Toba Tek Singh',4);
INSERT INTO cities VALUES (334,'Turbat',3);
INSERT INTO cities VALUES (335,'Ubaro',3);
INSERT INTO cities VALUES (336,'Uggokie',4);
INSERT INTO cities VALUES (337,'Umer Kot',3);
INSERT INTO cities VALUES (338,'Upper Topa',1);
INSERT INTO cities VALUES (339,'Vehari',5);
INSERT INTO cities VALUES (340,'Wah Cantt',1);
INSERT INTO cities VALUES (341,'Warburton',4);
INSERT INTO cities VALUES (342,'Wazirabad',4);
INSERT INTO cities VALUES (343,'Yazman Mandi',5);
INSERT INTO cities VALUES (344,'Zafar Wal',4);
